service: Test

provider:
  name: aws
  region: eu-central-1

resources:
  Resources:
    WebsiteBucketS3:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./config.json):BucketS3}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: ${file(./config.json):BucketS3}
        PolicyDocument:
          Statement:
            - Action:
                - "s3:GetObject"
              Effect: "Allow"
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - ${file(./config.json):BucketS3}
                    - "/*"
              Principal: "*"

    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${file(./config.json):TableDynamoDB}